---
title: "Final Code"
author: 'ALA Mode (Group 2): Anja Shahu, Anna Wuest, Ligia Flores'
date: "12/4/2020"
output: pdf_document
---

```{r library_load, results = "hide", message = FALSE}
library(tidyverse)
library(RColorBrewer)
```

```{r data_load, results = "hide"}
url <- "https://meps.ahrq.gov/mepsweb/data_files/pufs/h209dat.zip"
download.file(url, temp <- tempfile())
meps_path <- unzip(temp, exdir = tempdir())
source("https://meps.ahrq.gov/mepsweb/data_stats/download_data/pufs/h209/h209ru.txt")
unlink(temp) 
```

```{r reduce_data}
# creating a reduced data frame including only the variables that we'll be considering
h209red <- data.frame("pap" = h209$ADPAP42,
                      "region" = h209$REGION18,
                      "race" = h209$RACETHX,
                      "age" = h209$AGE18X,
                      "marital_stat" = h209$MARRY18X,
                      "educ" = h209$EDUCYR,
                      "smoke_freq" = h209$OFTSMK53, 
                      "income_indiv" = h209$TTLP18X,
                      "income_fam" = h209$FAMINC18,
                      "income_percpov" = h209$POVLEV18,
                      "hrsworked_rd1" = h209$HOUR31H,
                      "hrsworked_rd2" = h209$HOUR42H,
                      "hrsworked_rd3" = h209$HOUR53H,
                      "limitation" = h209$ACTLIM31, 
                      "menhlth_rd1" = h209$MNHLTH31, 
                      "menhlth_rd2" = h209$MNHLTH42, 
                      "menhlth_rd3" = h209$MNHLTH53, 
                      "genhlth_rd1" = h209$RTHLTH31,
                      "genhlth_rd2" = h209$RTHLTH42,
                      "genhlth_rd3" = h209$RTHLTH53,
                      "totexp" = h209$TOTEXP18,
                      "outofpocket_exp" = h209$TOTSLF18,
                      "afford_care" = h209$AFRDCA42,
                      "have_usc" = h209$HAVEUS42,
                      "dist_from_usc" = h209$TMTKUS42,
                      "rch_usc_byphn" = h209$PHNREG42,
                      "usc_offhrs_nw" = h209$OFFHOU42,
                      "usc_asks_abt_trts" = h209$TREATM42,
                      "usc_asks_hlp_dec" = h209$DECIDE42,
                      "usc_expln_options" = h209$EXPLOP42,
                      "inscov_gen_2018" = h209$INSCOV18) 

rm(h209) # remove original data set from environment

h209red <- h209red %>% 
  as_tibble() %>% 
  filter(pap != -1) %>% # filtering out the people who were not asked pap smear question
  filter(age >= 21 & age <= 65) # filtering to women ages 21-65 (note there was 1 inapplicable person that was filtered out as a result of this but I thought that was fine)
```

```{r}
## inputting NAs into hours worked variables
h209red$hrsworked_rd1[h209red$hrsworked_rd1 == -1] <- NA
h209red$hrsworked_rd2[h209red$hrsworked_rd2 == -1] <- NA
h209red$hrsworked_rd3[h209red$hrsworked_rd3 == -1] <- NA

# hours worked (rounded average)
h209red <- h209red %>% rowwise() %>%
  mutate(hrs_worked_avg = round(mean(c(hrsworked_rd1, hrsworked_rd2, hrsworked_rd3), na.rm = TRUE)))

h209red$hrs_worked_avg[is.nan(as.numeric(h209red$hrs_worked_avg))] <- NA

summary(h209red$hrs_worked_avg) # too many missing variables to use
```

```{r}
# re-calculating the mental and general health variables

# perceived mental heath adding NA
h209red$menhlth_rd1[h209red$menhlth_rd1 == -8 ]<- NA
h209red$menhlth_rd1[h209red$menhlth_rd1 == -1 ]<- NA

h209red$menhlth_rd2[h209red$menhlth_rd2 == -7 ]<- NA
h209red$menhlth_rd2[h209red$menhlth_rd2 == -8 ]<- NA

h209red$menhlth_rd3[h209red$menhlth_rd3 == -7 ]<- NA
h209red$menhlth_rd3[h209red$menhlth_rd3 == -8 ]<- NA
h209red$menhlth_rd3[h209red$menhlth_rd3 == -1 ]<- NA

# perceived mental health, rounded average for each group
h209red <- h209red %>% rowwise() %>%
  mutate(menhlth_avg = round(mean(c(menhlth_rd1, menhlth_rd2, menhlth_rd3), na.rm=TRUE)))

summary(h209red$menhlth_avg)

# perceived mental health converted to factor
h209red <- h209red %>% 
  mutate(menhlth_avg_f = factor(menhlth_avg, 
                                levels = c("5", "4", "3", "2", "1"))) %>%
  mutate(menhlth_avg_f = fct_recode(menhlth_avg_f,
                                    "poor" = "5",
                                    "fair" = "4",
                                    "good" = "3",
                                    "very good" = "2",
                                    "excellent" = "1"))


# re-calculating the general health variables

# perceived general heath NA
h209red$genhlth_rd1[h209red$genhlth_rd1 == -8 ] <- NA
h209red$genhlth_rd1[h209red$genhlth_rd1 == -1 ] <- NA

h209red$genhlth_rd2[h209red$genhlth_rd2 == -8 ] <- NA

h209red$genhlth_rd3[h209red$genhlth_rd3 == -7 ] <- NA
h209red$genhlth_rd3[h209red$genhlth_rd3 == -8 ] <- NA
h209red$genhlth_rd3[h209red$genhlth_rd3 == -1 ] <- NA

# perceived mental health, rounded average of each group
h209red <- h209red %>% rowwise() %>%
  mutate(genhlth_avg = round(mean(c(genhlth_rd1, genhlth_rd2, genhlth_rd3), na.rm=TRUE)))

summary(h209red$genhlth_avg)

# perceived general health converted to factor
h209red <- h209red %>% 
  mutate(genhlth_avg_f = factor(genhlth_avg, 
                                levels = c("5", "4", "3", "2", "1"))) %>%
  mutate(genhlth_avg_f = fct_recode(genhlth_avg_f,
                                   "poor" = "5",
                                   "fair" = "4",
                                   "good" = "3",
                                   "very good" = "2",
                                   "excellent" = "1"))
```

```{r}
# creating factor versions of other categorical variables 

# pap status
h209red <- h209red %>% 
  mutate(pap_f = factor(pap, 
                        levels = c("1", "2", "-15"))) %>%
  mutate(pap_f = fct_recode(pap_f, 
                            "yes" = "1",
                            "no" = "2",
                            NULL = "-15"))

# region
h209red <- h209red %>% 
  mutate(region_f = factor(region, 
                           levels = c("1", "2", "3", "4"))) %>%
  mutate(region_f = fct_recode(region_f, 
                               "northeast" = "1",
                               "midwest" = "2",
                               "south" = "3",
                               "west" = "4"))

# race
h209red <- h209red %>% 
  mutate(race_f = factor(race, 
                         levels = c("2", "1", "3", "4", "5"))) %>%
  mutate(race_f = fct_recode(race_f, 
                             "white" = "2",
                             "hispanic" = "1",
                             "black" = "3",
                             "asian" = "4",
                             "other or multiple races" = "5"))

# marital status
h209red <- h209red %>% 
  mutate(marital_stat_f = factor(marital_stat, 
                                 levels = c("5", "1", "2", "3", "4"))) %>%
  mutate(marital_stat_f = fct_recode(marital_stat_f,
                                     "never married" = "5",
                                     "married" = "1",
                                     "widowed" = "2",
                                     "divorced" = "3",
                                     "seperated" = "4"))
# education
h209red <- h209red %>%
  mutate(educ_f = factor(educ)) %>%
  mutate(educ_f = fct_collapse(educ_f,
                               "none or any elementary" = c("0", "1", "2", "3", "4", "5", "6", "7", "8"),
                               "any high school" = c("9", "10", "11", "12"),
                               "any college" = c("13", "14", "15", "16", "17"),
                               NULL = "-15",
                               NULL = c("-8", "-7"))) 
  
# smoking frequency
h209red <- h209red %>% 
  mutate(smoke_freq_f = factor(smoke_freq,
                               levels = c("3", "2", "1", "-8", "-7", "-1"))) %>%
  mutate(smoke_freq_f = fct_recode(smoke_freq_f, 
                                   "never" = "3", 
                                   "some days" = "2", 
                                   "every day" = "1", 
                                   NULL = "-8", 
                                   NULL = "-7", 
                                   NULL = "-1"))

# limitation
h209red <- h209red %>% 
  mutate(limitation_f = factor(limitation,
                               levels = c("2", "1", "-8", "-7", "-1"))) %>%
  mutate(limitation_f = fct_recode(limitation_f,
                                   "no" = "2", 
                                   "yes" = "1",
                                   NULL = "-8",
                                   NULL = "-7",
                                   NULL = "-1"))


# ability to afford care
h209red <- h209red %>% 
  mutate(afford_care_f = factor(afford_care, 
                                levels = c("2", "1", "-8", "-7"))) %>%
  mutate(afford_care_f = fct_recode(afford_care_f,
                                    "no" = "2",
                                    "yes" = "1",
                                    NULL = "-8",
                                    NULL = "-7"))

# usual source of care status
h209red <- h209red %>% 
  mutate(have_usc_f = factor(have_usc, 
                             levels = c("2", "1", "-8", "-7"))) %>%
  mutate(have_usc_f = fct_recode(have_usc_f,
                                 "no" = "2",
                                 "yes" = "1",
                                 NULL = "-8",
                                 NULL = "-7"))

# distance from provider
h209red <- h209red %>% 
  mutate(dist_from_usc = ifelse(have_usc_f == "no", 
                                -100, 
                                dist_from_usc)) %>% # creating level for not having a provider
  mutate(dist_from_usc_f = factor(dist_from_usc, 
                                  levels = c("1", "2", "3", "4", "5", "6", "-100", "-8", "-7", "-1"))) %>%
  mutate(dist_from_usc_f = fct_recode(dist_from_usc_f,
                                      "<15" = "1",
                                      "15 to 30" = "2",
                                      "31 to 60" = "3",
                                      "61 to 90" = "4",
                                      "91 to 120" = "5",
                                      ">120" = "6",
                                      "no usc" = "-100",
                                      NULL = "-8",
                                      NULL = "-7",
                                      NULL = "-1"))

# ability to reach provider by phone
h209red <- h209red %>% 
  mutate(rch_usc_byphn = ifelse(have_usc_f == "no", 
                                -100, 
                                rch_usc_byphn)) %>% # creating level for not having a provider
  mutate(rch_usc_byphn_f = factor(rch_usc_byphn, 
                                  levels = c("4", "3", "2", "1", "-100", "-8", "-7", "-1"))) %>%
  mutate(rch_usc_byphn_f = fct_recode(rch_usc_byphn_f,
                                      "not at all difficult" = "4",
                                      "not too difficult" = "3",
                                      "somewhat difficult" = "2",
                                      "very difficult" = "1",
                                      "no usc" = "-100",
                                      NULL = "-8",
                                      NULL = "-7",
                                      NULL = "-1"))

# provider offers office hours during nights/weekends
h209red <- h209red %>% 
  mutate(usc_offhrs_nw = ifelse(have_usc_f == "no", 
                                -100, 
                                usc_offhrs_nw)) %>% # creating level for not having a provider
  mutate(usc_offhrs_nw_f = factor(usc_offhrs_nw, 
                                  levels = c("-100", "2", "1", "-8", "-7", "-1"))) %>%
  mutate(usc_offhrs_nw_f = fct_recode(usc_offhrs_nw_f,
                                      "no usc" = "-100",
                                      "no" = "2",
                                      "yes" = "1",
                                      NULL = "-8",
                                      NULL = "-7",
                                      NULL = "-1"))
# provider asks about treatments
h209red <- h209red %>% 
  mutate(usc_asks_abt_trts = ifelse(have_usc_f == "no", 
                                   -100, 
                                   usc_asks_abt_trts)) %>% # creating level for not having a provider
  mutate(usc_asks_abt_trts_f = factor(usc_asks_abt_trts, 
                                      levels = c("-100", "2", "1", "-8", "-7", "-1"))) %>%
  mutate(usc_asks_abt_trts_f = fct_recode(usc_asks_abt_trts_f,
                                          "no usc" = "-100",
                                          "no" = "2",
                                          "yes" = "1",
                                          NULL = "-8",
                                          NULL = "-7",
                                          NULL = "-1"))

# provider asks person to help make decisions
h209red <- h209red %>% 
   mutate(usc_asks_hlp_dec = ifelse(have_usc_f == "no", 
                                    -100, 
                                    usc_asks_hlp_dec)) %>% # creating level for not having a provider
  mutate(usc_asks_hlp_dec_f = factor(usc_asks_hlp_dec, 
                                     levels = c("-100", "1", "2", "3", "4", "-8", "-7", "-1"))) %>%
  mutate(usc_asks_hlp_dec_f = fct_recode(usc_asks_hlp_dec_f,
                                         "no usc" = "-100",
                                         "never" = "1",
                                         "sometimes" = "2",
                                         "usually" = "3",
                                         "always" = "4",
                                         NULL = "-8",
                                         NULL = "-7",
                                         NULL = "-1"))

# provider presents and explains all options
h209red <- h209red %>% 
  mutate(usc_expln_options = ifelse(have_usc_f == "no", 
                                    -100, 
                                    usc_expln_options)) %>% # creating level for not having a provider
  mutate(usc_expln_options_f = factor(usc_expln_options, 
                                      levels = c("-100", "2", "1", "-8", "-7", "-1"))) %>%
  mutate(usc_expln_options_f = fct_recode(usc_expln_options_f,
                                          "no usc" = "-100",
                                          "no" = "2",
                                          "yes" = "1",
                                          NULL = "-8",
                                          NULL = "-7",
                                          NULL = "-1"))

# insurance indicator in 2018
h209red <- h209red %>% 
  mutate(inscov_gen_2018_f = factor(inscov_gen_2018, 
                                    levels = c("1", "2", "3"))) %>%
  mutate(inscov_gen_2018_f = fct_recode(inscov_gen_2018_f,
                                        "any private" = "1",
                                        "public only" = "2",
                                        "uninsured" = "3"))
```

```{r}
# creating combined provider availability variable using 1) distance 2) ability to reach by phone 3) office hours
h209red <- h209red %>% 
  mutate(dist_from_usc = ifelse(have_usc_f == "no", 0, dist_from_usc))
h209red$dist_from_usc[h209red$dist_from_usc == -8] <- NA
h209red$dist_from_usc[h209red$dist_from_usc == -7] <- NA

h209red <- h209red %>% 
  mutate(rch_usc_byphn = ifelse(have_usc_f == "no", 0, rch_usc_byphn))
h209red$rch_usc_byphn[h209red$rch_usc_byphn == -8] <- NA
h209red$rch_usc_byphn[h209red$rch_usc_byphn == -7] <- NA

h209red <- h209red %>% 
  mutate(usc_offhrs_nw = ifelse(have_usc_f == "no", 0, usc_offhrs_nw))
h209red$usc_offhrs_nw[h209red$usc_offhrs_nw == -8] <- NA
h209red$usc_offhrs_nw[h209red$usc_offhrs_nw == -7] <- NA
h209red$usc_offhrs_nw[h209red$usc_offhrs_nw == -1] <- NA

# creating binary access variables to use for making combined score
# give 0 to those w/o provider
# give 1 to people who have to travel 30+ minutes
# and give 2 to people who are within 30 min
h209red <- h209red %>% mutate(dist_from_usc_bin = ifelse(dist_from_usc %in% c(1, 2), 2,
                                                         ifelse(dist_from_usc %in% c(3, 4, 5, 6), 1,
                                                                dist_from_usc)))

# give 0 to those w/o provider
# and give 1 to people who answer somewhat difficult or very difficult 
# give 2 to people who answer not at all difficult or not too difficult
h209red <- h209red %>% mutate(rch_usc_byphn_bin = ifelse(rch_usc_byphn %in% c(1, 2), 1,
                                                         ifelse(rch_usc_byphn %in% c(3, 4, 5, 6), 2,
                                                                rch_usc_byphn)))

# give 0 to those w/o provider
# and give 1 to people whose provider does not offer office hours during night/weekend 
# give 2 to people whose provider does offer
h209red <- h209red %>% mutate(usc_offhrs_nw_bin = ifelse(usc_offhrs_nw == 1, 2,
                                                         ifelse(usc_offhrs_nw == 2, 1,
                                                                usc_offhrs_nw)))

# finally creating combined availability score from binary variables
h209red <- h209red %>% 
  mutate(usc_access_score = dist_from_usc_bin + rch_usc_byphn_bin + usc_offhrs_nw_bin)
```

```{r}
# creating combined provider satisfaction variable using 1) asking about treatments 2) asks person to help w/ decisions 3) explains all options
h209red <- h209red %>% 
  mutate(usc_asks_abt_trts = ifelse(have_usc_f == "no", 0, usc_asks_abt_trts))
h209red$usc_asks_abt_trts[h209red$usc_asks_abt_trts == -8] <- NA
h209red$usc_asks_abt_trts[h209red$usc_asks_abt_trts == -7] <- NA

h209red <- h209red %>% 
   mutate(usc_asks_hlp_dec = ifelse(have_usc_f == "no", 0, usc_asks_hlp_dec)) 
h209red$usc_asks_hlp_dec[h209red$usc_asks_hlp_dec == -8] <- NA
h209red$usc_asks_hlp_dec[h209red$usc_asks_hlp_dec == -7] <- NA

h209red <- h209red %>% 
  mutate(usc_expln_options = ifelse(have_usc_f == "no", 0, usc_expln_options))
h209red$usc_expln_options[h209red$usc_expln_options == -8] <- NA
h209red$usc_expln_options[h209red$usc_expln_options == -7] <- NA


# creating binary access variables to use for making combined score
# give 0 to those w/o provider
# give 1 to those who answered no
# and give 2 to those who answered yes
h209red <- h209red %>% mutate(usc_asks_abt_trts_bin = ifelse(usc_asks_abt_trts == 1, 2,
                                                             ifelse(usc_asks_abt_trts == 2, 1,
                                                                    usc_asks_abt_trts)))

# give 0 to those w/o provider
# and give 1 to those who answered never or sometimes
# give 2 to those who answered usually or always
h209red <- h209red %>% mutate(usc_asks_hlp_dec_bin = ifelse(usc_asks_hlp_dec %in% c(1, 2), 1,
                                                            ifelse(usc_asks_hlp_dec %in% c(3, 4), 2,
                                                                   usc_asks_hlp_dec)))

# give 0 to those w/o provider
# and give 1 to people who answer no
# give 2 to those who answered yes
h209red <- h209red %>% mutate(usc_expln_options_bin = ifelse(usc_expln_options == 1, 2,
                                                             ifelse(usc_expln_options == 2, 1,
                                                                    usc_expln_options)))

# finally creating combined satisfaction score from binary variables
h209red <- h209red %>% 
  mutate(usc_satisf_score = usc_asks_abt_trts_bin + usc_asks_hlp_dec_bin + usc_expln_options_bin)
```


```{r}
# creating our data set of variables we'll use in our modeling
df <- h209red %>% dplyr::select(pap_f, age, income_indiv, income_fam, totexp, 
                                outofpocket_exp, genhlth_avg_f, region_f, 
                                race_f, marital_stat_f, educ_f, smoke_freq_f, 
                                limitation_f, afford_care_f, have_usc_f,
                                inscov_gen_2018_f)  %>%
  mutate(pap_num = as.numeric(pap_f) - 1) # create numeric pap variable

# create complete cases data set for modeling
cc_df <- df %>% drop_na()
```

```{r}
# check for high correlation between variables
cc_df_num <- data.frame(cc_df$pap_num, cc_df$age, cc_df$income_indiv, 
                        cc_df$income_fam, cc_df$totexp, cc_df$outofpocket_exp,
                        as.numeric(cc_df$genhlth_avg_f) - 1,
                        as.numeric(cc_df$region_f) - 1,
                        as.numeric(cc_df$race_f) - 1,
                        as.numeric(cc_df$marital_stat_f) - 1,
                        as.numeric(cc_df$educ_f) - 1,
                        as.numeric(cc_df$smoke_freq_f) - 1,
                        as.numeric(cc_df$limitation_f) - 1,
                        as.numeric(cc_df$afford_care_f) - 1,
                        as.numeric(cc_df$have_usc_f) - 1,
                        as.numeric(cc_df$inscov_gen_2018_f) - 1)
names <- colnames(cc_df)[2:16]
colnames(cc_df_num) <- c("pap_num", names)
correlation_matrix <- round(cor(cc_df_num), digits = 2) # looks pretty good
```

```{r}
library(caret)
library(leaps)
library(LogisticDx)
library(ResourceSelection)
library(MASS)
library(car)
library(caret)
library(pROC)
```

## Associational modeling
Now we will create associational models on the full complete cases data set.
```{r}
# full model
mod_full <- glm(pap_num ~ age + income_indiv + income_fam + totexp + outofpocket_exp + genhlth_avg_f + region_f + race_f + marital_stat_f + educ_f + smoke_freq_f + limitation_f + afford_care_f + have_usc_f + inscov_gen_2018_f, family = binomial(), data = cc_df) 
summary(mod_full)
vif(mod_full) # correlation looks good

hoslem.test(cc_df$pap_num, fitted(mod_full), g = 10) # good fit for full model!
gof(mod_full, g = 10)
```

```{r}
# forward/backward selection model

# forward model selection
mod_forw <- step(glm(pap_num ~ 1, data = cc_df, family = binomial()), ~ age + income_indiv + income_fam + totexp + outofpocket_exp + genhlth_avg_f + region_f + race_f + marital_stat_f + educ_f + smoke_freq_f + limitation_f + afford_care_f + have_usc_f + inscov_gen_2018_f, direction = "forward")
summary(mod_forw)
vif(mod_forw) # correlation looks good

# backward model selection
mod_back <- step(mod_full, direction = "backward")
summary(mod_back) # forward and backward selection produce the same model here

hoslem.test(cc_df$pap_num, fitted(mod_back), g = 10) # good fit for forward/backward model!
gof(mod_back, g = 10)
```

```{r}
# testing if nonlinear terms are needed for age

# trying quadratic
mod_age_quad <- glm(pap_num ~ age + I(age^2) + income_indiv + income_fam + totexp + race_f + marital_stat_f + educ_f + smoke_freq_f + limitation_f + afford_care_f + have_usc_f + inscov_gen_2018_f, family = binomial(), data = cc_df)
summary(mod_age_quad)
# p < 0.05 for age^2 term so makes sense to keep quadratic term

hoslem.test(cc_df$pap_num, fitted(mod_age_quad), g = 10) # good fit
gof(mod_age_quad, g = 10)

# trying cubic spline
library(splines)
library(splines2) 

# fit cubic spline with 3 knots
mod_age_cubic_spline <- glm(pap_num ~ bSpline(age, df = 6, degree = 3) + income_indiv + income_fam + totexp + race_f + marital_stat_f + educ_f + smoke_freq_f + limitation_f + afford_care_f + have_usc_f + inscov_gen_2018_f, family = binomial(), data = cc_df)
summary(mod_age_cubic_spline)

hoslem.test(cc_df$pap_num, fitted(mod_age_cubic_spline), g = 10) # good fit
gof(mod_age_cubic_spline, g = 10)

anova(mod_back, mod_age_cubic_spline, test = "Chisq") 
# LRT p-value < 0.05 so makes sense to have this spline term


# testing to see if quadratic age is sufficient or we need cubic spline
# we can do this since quad age model is nested within cubic spline model
anova(mod_age_quad, mod_age_cubic_spline, test = "Chisq") 
# p-value < 0.05 so makes sense to use cubic spline term instead of quad term only
```

```{r}
# Building off the spline model to add interactions

# interaction model 1
mod_spline_interaction1 <- glm(pap_num ~ bSpline(age, df = 6, degree = 3) + income_indiv + income_fam + totexp + race_f + marital_stat_f + educ_f + smoke_freq_f + limitation_f + afford_care_f + have_usc_f + inscov_gen_2018_f + marital_stat_f*income_fam, family = binomial(), data = cc_df)
summary(mod_spline_interaction1)

hoslem.test(cc_df$pap_num, fitted(mod_spline_interaction1), g = 10) # good fit
gof(mod_spline_interaction1, g = 10)

anova(mod_age_cubic_spline, mod_spline_interaction1, test = "Chisq") 
# LRT p-value < 0.05 so makes sense to keep this interaction

# interaction model 2
mod_spline_interaction2 <- glm(pap_num ~ bSpline(age, df = 6, degree = 3) + income_indiv + income_fam + totexp + race_f + marital_stat_f + educ_f + smoke_freq_f + limitation_f + afford_care_f + have_usc_f + inscov_gen_2018_f + marital_stat_f*income_fam + educ_f*totexp, family = binomial(), data = cc_df)
summary(mod_spline_interaction2)

hoslem.test(cc_df$pap_num, fitted(mod_spline_interaction2), g = 10) # good fit
gof(mod_spline_interaction2, g = 10)

anova(mod_spline_interaction1, mod_spline_interaction2, test = "Chisq") 
# LRT p-value < 0.05 so makes sense to keep this interaction
```

```{r}
# comparing AIC for all the association models we've built so far
AIC(mod_full,
    mod_back,
    mod_age_quad,
    mod_age_cubic_spline,
    mod_spline_interaction1,
    mod_spline_interaction2)

# pick one of these association models as the final one 
# we should be good with these 6 and don't want to run anything more complicated which will make interpretation hard
```


## Prediction modeling
Now we're working on creating prediction models using the training set and then testing it on the testing set.
```{r}
# build test and train set
set.seed(1)
train_index <- createDataPartition(cc_df$pap_num, times = 1, p = 0.7, list = FALSE)
train_set <- cc_df[train_index, ]
test_set <- cc_df[-train_index, ]
```

```{r}
# create function for looking at prediction metrics
pred_metrics <- function(model, cutoff) {
  p_hat <- predict(model, newdata = test_set, type = "response")
  y_hat <- ifelse(p_hat > cutoff, "no", "yes")
  confusion <- confusionMatrix(data = factor(y_hat, levels = c("yes", "no")),
                               reference = test_set$pap_f)
  
  roc <- roc(test_set$pap_num, p_hat)
  auc <- auc(roc)
  
  result <- list(p_hat = p_hat, 
                 y_hat = y_hat, 
                 confusion = confusion, 
                 roc = roc, 
                 auc = auc)
  result
}
```

```{r}
# full model
fit_full <- glm(pap_num ~ age + income_indiv + income_fam + totexp + outofpocket_exp + genhlth_avg_f + region_f + race_f + marital_stat_f + educ_f + smoke_freq_f + limitation_f + afford_care_f + have_usc_f + inscov_gen_2018_f, family = binomial(), data = train_set)
summary(fit_full)
hoslem.test(train_set$pap_num, fitted(fit_full), g = 10) # good fit to training for full model

# now we see how accurate full model is for future data

# testing to see what p cutoff balances sensitivity and specificity best 
# so that we can use that cutoff when we run the prediction models at first
p_seq <- seq(0, 1, .01)
sensitivity <- rep(NA, length(p_seq))
specificity <- rep(NA, length(p_seq))
for (i in 1:length(p_seq)) {
  p_cutoff <- p_seq[i]
  prediction <- pred_metrics(fit_full, p_cutoff)
  confusion <- prediction$confusion
  sensitivity[i] <- confusion$byClass["Sensitivity"]
  specificity[i] <- confusion$byClass["Specificity"]
}
test_cutoff_df <- data.frame(p_seq, sensitivity, specificity) 
# cutoff of 0.26 looks best

# get prediction metrics for full fit
fit_full_pred_metrics <- pred_metrics(fit_full, 0.26)
fit_full_pred_metrics$confusion
fit_full_pred_metrics$auc
```

```{r}
# forward/backward selection 

# forward model selection
fit_forw <- step(glm(pap_num ~ 1, data = train_set, family = binomial()), ~ age + income_indiv + income_fam + totexp + outofpocket_exp + genhlth_avg_f + region_f + race_f + marital_stat_f + educ_f + smoke_freq_f + limitation_f + afford_care_f + have_usc_f + inscov_gen_2018_f, direction = "forward")
summary(fit_forw)

# backward model selection
fit_back <- step(fit_full, direction = "backward")
summary(fit_back)
# forward and backward selection produce the same model
hoslem.test(train_set$pap_num, fitted(fit_back), g = 10) # good fit to training for forward/backward model

# now we can see how forward/backward model performs on testing data
fit_back_pred_metrics <- pred_metrics(fit_back, 0.26)
fit_back_pred_metrics$confusion # better accuracy than full fit
fit_back_pred_metrics$auc # slightly worse auc than full fit
# going to use auc as the main comparison metric for picking the best prediction model since it looks over a range of p cutoffs rather than just p = 0.26 which we just arbritarly chose
```

```{r}
# going forward with building off of full model since it has better auc

# add nonlinear terms for age

# try quadratic first 
fit_age_quad <- glm(formula = pap_num ~ age + I(age^2) + income_indiv + income_fam + totexp + outofpocket_exp + genhlth_avg_f + region_f + race_f + marital_stat_f + educ_f + smoke_freq_f + limitation_f + afford_care_f + have_usc_f + inscov_gen_2018_f, family = binomial(), data = train_set)
hoslem.test(train_set$pap_num, fitted(fit_age_quad), g = 10) # good fit to training

# now we can see how it performs on testing data
fit_age_quad_pred_metrics <- pred_metrics(fit_age_quad, 0.26)
fit_age_quad_pred_metrics$auc # slightly better auc than full fit model

# try spline 
fit_age_cubic_spline <- glm(formula = pap_num ~ age + bSpline(age, df = 6, degree = 3) + income_indiv + income_fam + totexp + outofpocket_exp + genhlth_avg_f + region_f + race_f + marital_stat_f + educ_f + smoke_freq_f + limitation_f + afford_care_f + have_usc_f + inscov_gen_2018_f, family = binomial(), data = train_set)
hoslem.test(train_set$pap_num, fitted(fit_age_quad), g = 10) # good fit to training

# now we can see how it performs on testing data
fit_age_cubic_spline_pred_metrics <- pred_metrics(fit_age_cubic_spline, 0.26)
fit_age_cubic_spline_pred_metrics$auc # slightly lower auc than age quad model
```

```{r}
# building off of quad age model since it has the best auc so far 

# add interaction terms

# interaction 1
fit_age_quad_interaction1 <- glm(formula = pap_num ~ age + I(age^2) + income_indiv + income_fam + totexp + outofpocket_exp + genhlth_avg_f + region_f + race_f + marital_stat_f + educ_f + smoke_freq_f + limitation_f + afford_care_f + have_usc_f + inscov_gen_2018_f + marital_stat_f*income_fam, family = binomial(), data = train_set)

hoslem.test(train_set$pap_num, fitted(fit_age_quad_interaction1), g = 10) # good fit to training

# now we can see how it performs on testing data
fit_age_quad_interaction1_pred_metrics <- pred_metrics(fit_age_quad_interaction1, 0.26)
fit_age_quad_interaction1_pred_metrics$auc # slightly better auc than quad age model

# interaction 2
fit_age_quad_interaction2 <- glm(formula = pap_num ~ age + I(age^2) + income_indiv + income_fam + totexp + outofpocket_exp + genhlth_avg_f + region_f + race_f + marital_stat_f + educ_f + smoke_freq_f + limitation_f + afford_care_f + have_usc_f + inscov_gen_2018_f + marital_stat_f*income_fam + educ_f*totexp, family = binomial(), data = train_set)

hoslem.test(train_set$pap_num, fitted(fit_age_quad_interaction2), g = 10) # good fit to training

# now we can see how it performs on testing data
fit_age_quad_interaction2_pred_metrics <- pred_metrics(fit_age_quad_interaction2, 0.26)
fit_age_quad_interaction2_pred_metrics$auc # slightly better auc from interaction 1 so we could keep
```

```{r}
# build and compare more prediction models 
# since we don't need to worry about interpretation for our prediction model, feel free to make models as complex as you want 
```

